In [1]:
import numpy as np

In [2]:
ar=np.array([100,200,300])
ar

array([100, 200, 300])

In [3]:
type(ar)

numpy.ndarray

In [4]:
ar2=np.array([3.2,4.5,5.6])
ar2

array([3.2, 4.5, 5.6])

In [5]:
ar3=np.array([3.2,4.5,8,9])
ar3

array([3.2, 4.5, 8. , 9. ])

In [6]:
ar4=np.array([3.2,4.5,"cs"])
ar4

array(['3.2', '4.5', 'cs'], dtype='<U32')

In [7]:
ar5=np.array([3.2,4.5,8,9],dtype=int)
ar5

array([3, 4, 8, 9])

In [ ]:
ar=np.array([100,200,300,400,500])
#perfomr indexing and slicing (same as list)

In [8]:
np.array([[10,20,30],[40,50,60],[70,80,90]])

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
# different ways of creating array.

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.random.randn(6)  # choose n random numbers from 0-1 and create an array.

array([ 0.82322947, -0.68104401, -2.05659479, -0.15230985,  0.60508013,
       -0.04216279])

In [15]:
np.random.randn(3,3)

array([[ 0.22453166, -1.07050851,  1.76119661],
       [-0.38227436,  0.54585444, -0.35399241],
       [-0.1987203 ,  1.60286923,  0.45705805]])

In [16]:
ar6=np.array([1,2,3,6,8,9,10])
ar6

array([ 1,  2,  3,  6,  8,  9, 10])

In [20]:
np.mean(ar6)

5.571428571428571

In [19]:
np.median(ar6)

6.0

In [21]:
np.sum(ar6)

39

In [22]:
np.sqrt(ar6)

array([1.        , 1.41421356, 1.73205081, 2.44948974, 2.82842712,
       3.        , 3.16227766])