In [2]:
import numpy as np

In [2]:
a1=np.array([100,200,300,400,500])
a1

array([100, 200, 300, 400, 500])

In [18]:
a1[1:4]


array([200, 300, 400])

In [3]:
a2=np.arange(1,11)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a3=np.array([[10,20,30],[40,50,60]])
a3[0,1]

20

In [24]:
#transpose
a3.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [25]:
np.min(a3)

10

In [26]:
np.max(a3)

60

In [14]:
l=[]
for i in range(0,2):
    for j in range(0,3):
        l.append(a3[i,j])

In [15]:
l

[10, 20, 30, 40, 50, 60]

In [16]:
a3[:]

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
a3[::-1]

array([[40, 50, 60],
       [10, 20, 30]])

In [19]:
d=np.arange(2,10)
d

array([2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#quantiles
#Q1= 0.25
#Q2=0.50
#Q3=0.75


3.75

In [33]:
np.quantile(d,0.25)

3.75

In [31]:
np.quantile(d,0.50)


5.5

In [32]:
np.quantile(d,0.75)

7.25

In [23]:
np.mean(d)

4.5

In [24]:
np.median(d)

4.5

In [25]:
np.sum(d)

27

In [28]:
np.sqrt(d)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        ])

In [8]:
u=np.random.randn(4)
u

array([-1.56590351,  0.00883257, -1.35907819,  0.11590352])

In [10]:
u=np.random.randn(4,4)
u

array([[-2.83229104, -1.36915201,  0.44233274, -0.50246921],
       [ 0.08375136, -0.0433359 ,  0.84244116, -0.19621031],
       [-0.64367191, -0.0301298 ,  0.01398356,  0.88431772],
       [ 1.23546023,  1.14559791, -0.25316374,  2.20638868]])

In [12]:
#dimension of an array
u.ndim

2

In [14]:
#rows and cols in array
u.shape

(4, 4)

In [16]:
#returns no. of elements
u.size

16

In [17]:
len(u)

4

In [2]:
np.random.randint(low=1,high=10,size=(2,5))

array([[3, 9, 8, 4, 8],
       [1, 8, 9, 3, 4]])

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
#np.random.random(10)=randomly generates the array as per given no. of elements

a1=np.random.random(10)
a1

array([0.16740581, 0.07303911, 0.84807729, 0.0945765 , 0.72190252,
       0.78667877, 0.07268859, 0.20186645, 0.97762721, 0.12515348])

In [39]:
#reshape=changing dimensions

a1.reshape(5,2)

array([[0.67340247, 0.08122076],
       [0.21408047, 0.20641692],
       [0.44895838, 0.84262907],
       [0.46536729, 0.30185271],
       [0.37937685, 0.05256826]])

In [44]:
#3d array using randn and reshape
#the product of reshape() should match the randn(number)

#                    reshape(card,row,col)
a=np.random.randn(18).reshape(3,3,2)
a

array([[[ 0.08219092,  0.79281744],
        [-0.65565054,  1.27122891],
        [ 0.17191307, -0.62164705]],

       [[ 1.43286027,  0.60943991],
        [-0.91535789,  1.85137507],
        [ 1.47774762, -0.28627691]],

       [[ 0.23608803,  1.24967129],
        [ 0.56575033,  0.11474634],
        [ 0.47803862,  2.13013347]]])

In [48]:
a4=[[10,11,12,13,14],[15,16,17,18,19]]

#sum row-wise

a=np.array(a4)
a.sum(axis=1)

array([60, 85])

In [49]:
#sum col-wise

a=np.array(a4)
a.sum(axis=0)

array([25, 27, 29, 31, 33])

In [52]:
#sum all over

a=np.array(a4)
a.sum()

145

In [53]:
#max value row-wise

a=np.array(a4)
a.max(axis=1)

array([14, 19])

In [54]:
#max value col-wise

a=np.array(a4)
a.max(axis=0)

array([15, 16, 17, 18, 19])

In [55]:
#max valueover all

a=np.array(a4)
a.max()

19

In [16]:
s1=[[1,2,3],[7,8,9]]
s2=[[4,5,6],[10,11,12]]
#use double brackets otherwise gives list error
np.concatenate((s1,s2))

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

In [11]:
np.concatenate((s1,s2),axis=1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
np.concatenate((s1,s2),axis=0)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

In [13]:
c=[]
np.append(c,s1)


array([1., 2., 3., 7., 8., 9.])

In [21]:
d=[66,77,88]
np.insert(s2,2,d,axis=0)

array([[ 4,  5,  6],
       [10, 11, 12],
       [66, 77, 88]])

In [23]:
np.delete(s2,2)

array([ 4,  5, 10, 11, 12])

In [ ]:
#BROADING CASTING

In [25]:


#addition

a1=np.array([100,200,300])
r=a1+50
r

array([150, 250, 350])

In [28]:
p1=np.array([[10,20,30],[3,4,5]])
p1

array([[10, 20, 30],
       [ 3,  4,  5]])

In [30]:
p2=np.array([[50,30,70],[13,14,15]])
p2

array([[50, 30, 70],
       [13, 14, 15]])

In [32]:
#numpy arrays addition
r2=p1+p2
r2

array([[ 60,  50, 100],
       [ 16,  18,  20]])

In [ ]:
#BOOLEAN INDEXING
# T or F values are used for indexing 

In [33]:
p1=np.array([[10,20,30],[3,4,5]])
#it returns T or F for every element whether it satisfies the condition or not
p1>50

array([[False, False, False],
       [False, False, False]])

In [34]:
#to get only elements that satisfies the condition in array use:
p1[p1<30]

array([10, 20,  3,  4,  5])