# numpy vs list

In [ ]:
#memory consumption betwn numpy and list
import sys
import numpy as np
list1=list(range(1,1000))

print("size of an object=",(sys.getsizeof(list1)))


d=np.arange(1000)
print("size of entire array",(d.itemsize*d.size))

In [ ]:
#time comparision

import time
size=1000

list1=range(1000)
list2=range(1000)

initialtime=time.time()
print(initialtime)
op=[a*b for a,b in zip(list1,list2)]
endtime=time.time()-initialtime
print(time.time())
print("-----------------------------")

a1=np.arange(size)
a2=np.arange(size)
initialtime=time.time()
print(initialtime)
op=a1*a2
endtime=time.time()-initialtime
print(time.time())

# creating numpy array

In [2]:
import numpy as np

In [ ]:
a1=np.array([10,20,30,40])

In [ ]:
a1

In [ ]:
a2=np.array([10,20,30,'mystr'])

In [ ]:
a2

In [ ]:
a3=np.array([10,20,30,40],dtype='int')

In [ ]:
a3

In [ ]:
a4=np.array([10,20,30,40],dtype='float')

In [ ]:
a4

In [ ]:
a5=np.arange(1,10)

In [ ]:
a5

In [ ]:
a6=np.arange(1,10,2)

In [ ]:
a6

In [ ]:
a7=np.arange(10,0,-1)

In [ ]:
a7

In [5]:
#Return evenly spaced numbers over a specified interval
a8=np.linspace(1,21,num=7,endpoint=False)

In [6]:
a8

array([ 1.        ,  3.85714286,  6.71428571,  9.57142857, 12.42857143,
       15.28571429, 18.14285714])

In [ ]:
r=np.random.randn(5)
a9=np.array(r)

In [ ]:
a9

In [ ]:
r1=np.random.random(10)

In [ ]:
a10=np.array(r1)

In [ ]:
a10

In [17]:
a11=np.zeros((3,5,5),dtype=int)

In [18]:
a11

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [10]:
a12=np.ones(5)


In [11]:
a12

array([1., 1., 1., 1., 1.])

In [ ]:
# creating 2d array

In [1]:
a13=np.array([[10,20,30],[1,2,3],[5,67,7]])

NameError: ignored

In [ ]:
a13

In [12]:
a14=np.array([[[2,17],[45,78]],[[5,6],[100,101]],[[99,98],[97,96]]])

In [14]:
a14

array([[[  2,  17],
        [ 45,  78]],

       [[  5,   6],
        [100, 101]],

       [[ 99,  98],
        [ 97,  96]]])

In [ ]:
a14[0][1]

In [ ]:
a14[0][1][1]

In [23]:
a14.shape

(3, 2, 2)

# numpy properties

In [11]:
n1=np.array([10,20,30,40])

In [12]:
n1.dtype

dtype('int32')

In [19]:
od=np.array([[1,2,3],[4,5,6]])
od.ndim

2

In [20]:
od

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
od.shape

(2, 3)

In [24]:
od.size #total number of elements present.

6

In [25]:
len(od) #total number of rows

2

In [26]:
#lets understand difference betwn len and size
n2=np.array([[1,2,3],[4,5,6]])

In [27]:
n2.ndim

2

In [28]:
n2.size

6

In [29]:
len(n2)

2

In [30]:
od.itemsize  #return size (in bytes) of each element

4

In [19]:
od

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
newt=od.T #transpose

In [32]:
newt

array([[1, 4],
       [2, 5],
       [3, 6]])

# numpy indexing

In [ ]:
n3=np.array([100,200,300,400,500])

In [ ]:
n3[0]

In [ ]:
n3[0:3]

In [ ]:
n4=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
n4[1:,1:]

In [ ]:
n4[1:]

In [ ]:
n4[1][2]

In [ ]:
n4[1,2] #similar to n4[1][2]

In [ ]:
n4[1:,1:]

In [ ]:
n4[::-1,::-1]

In [ ]:
n4

In [ ]:
n4[:,:2]

# numpy function

In [33]:
myarr=np.array([1,2,3,4,5,6,7,8,9,])

In [34]:
np.mean(myarr)

5.0

In [35]:
np.median(myarr)

5.0

In [36]:
np.min(myarr)

1

In [37]:
np.max(myarr)

9

In [ ]:
#quantile 
# Q2 ---> 0.50
# Q1---> 0.25
# Q3 ---> 0.75


In [38]:
arr=np.array([20,2,7,1,34])

In [39]:
np.quantile(arr,0.50)

7.0

In [40]:
np.quantile(arr,0.25)

2.0

In [41]:
np.quantile(arr,0.75)  

#now find iqr , lowerlimit , upperlimit


20.0

In [ ]:
np.sin(90)

In [ ]:
np.log10(10)

In [ ]:
np.sqrt(225)

In [22]:
#reshaping 

In [42]:
n1=np.random.random(10) #pick 10 random values between 0-1

In [43]:
n1

array([0.34199991, 0.78907413, 0.83894827, 0.48733694, 0.97007655,
       0.73921325, 0.1114617 , 0.07009719, 0.28887929, 0.00960378])

In [44]:
n1.ndim

1

In [45]:
n1.size

10

In [48]:
n1.reshape(2,5)

array([[0.34199991, 0.78907413, 0.83894827, 0.48733694, 0.97007655],
       [0.73921325, 0.1114617 , 0.07009719, 0.28887929, 0.00960378]])

In [50]:
a = np.random.randn(24).reshape(2,3,4) #reshaping into 3d
a

array([[[-0.32630117, -0.74253067, -0.08346239, -0.22685495],
        [ 0.4087937 ,  0.2420292 ,  1.09872161,  1.08848337],
        [ 1.04213661, -0.84227916, -1.04173359,  0.01606187]],

       [[ 0.25203578,  0.47252435,  1.49686218, -0.36132292],
        [-0.40345314,  0.58888009, -0.14077344,  1.13440437],
        [ 1.24024407, -1.39305505, -2.50578422,  1.06733861]]])

In [51]:
ar = np.arange(10,20).reshape(2,5)
ar
# a.sum()
# a.sum(axis=0)
# a.sum(axis=1)
# a.max()
# a.min()
# a.max(axis=1)
# a.max(axis=0)
# a.mean()
# a.var()  - indicates spread of a data.
# a.std()

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
ar

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
ar.sum(axis=1) #horizontal flow


array([60, 85])

In [ ]:
ar.sum()

In [55]:
ar.sum(axis=0) #vertical flow

array([25, 27, 29, 31, 33])

In [57]:
ar

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
ar.max()

19

In [58]:
ar.max(axis=1) # finds horizontally

array([14, 19])

In [59]:
ar.max(axis=0) #finds vertically

array([15, 16, 17, 18, 19])

In [60]:
a1 = np.arange(1,7).reshape(2,3)    # this is arange function, similar to range funtion
b1 = np.arange(7,13).reshape(2,3)  

In [61]:
print(a1)
print(b1)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [62]:
np.concatenate((a1,b1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
np.concatenate((a1,b1),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [64]:
# 4.Append(array,list.of.elements) - used to add the elements in an array
c = np.arange(1,7)
c

array([1, 2, 3, 4, 5, 6])

In [65]:
np.append(c,[7,8,9])     #this is also a temprory, not inplace

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
c

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 5.Insert(array,index,element)- used to add element at specific index
d = np.arange(2,6)
d

In [ ]:
np.insert(d,0,100)

In [ ]:
d

In [38]:
# 6.Delete(array,list.of.elements.index)- used to delete elementof specific index
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [ ]:
np.delete(a,[1,2,3]) #this will delete values at given index position 2,3,4

In [ ]:
a

In [ ]:
#broadcasting

In [67]:
a2=np.array([100,200,300])
a2+50

array([150, 250, 350])

In [70]:
a1=np.array([[10,20,30],[3,4,5]])
a2=np.array([100,200,300])
a3=a1+a2

In [71]:
a3

array([[110, 220, 330],
       [103, 204, 305]])

In [72]:
a1=np.array([10,20,30,40])
a2=np.array([100,200,300,400])
a3=a1+a2

In [73]:
a3

array([110, 220, 330, 440])

In [74]:
np.array([[10,20,30],[90,89],[10,11,12]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
#boolean indexing

In [75]:
a=np.array([10,25,55,35,19,45,33])

In [76]:
a>20

array([False,  True,  True,  True, False,  True,  True])

In [77]:
a[a>20]

array([25, 55, 35, 45, 33])